### ISSUE TITLE
Does not work as a `dependency` of a nested addon

### ISSUE THREAD

**Issue by vitch** [dwickern/ember-chrome-devtools#2]
Firstly, thanks for this awesome addon!

We have an internal addon which is used by a number of applications and I wanted to be able to specify `ember-chrome-devtools` as a `dependency` (not `devDependency`) of that addon and have the goodness that it brings in all of our apps.

Unfortunately `ember-chrome-devtools` blows up because `this.app` is `undefined` in that circumstance and so `this.app.env` is not accessible.

I implemented a workaround in [this commit](https://github.com/vitch/ember-chrome-devtools/commit/47d13e92546494aab5c6b11126acb754f7e3d243) but I feel like there should be a better way. Any ideas?

**Comment by dwickern** [comment]
Apparently to work as a nested addon, you need to do this:
https://github.com/samselikoff/ember-cli-mirage/blob/master/index.js#L23-L39

Also, it should probably call `this._super.included.apply(this, arguments)` just to be safe.

A PR would be much appreciated

**Comment by vitch** [comment]
Thanks!

I'll try and put a PR together ASAP - realistically it will probably be a week or two out because I'm right in the middle of something...

**Comment by dwickern** [comment]
@vitch Did you have a chance to try out the fix?

**Comment by vitch** [comment]
Sorry for the massive delay! #9 addresses the problem in the more-preferred way. I've tested from an app which uses the dependency directly and in a nested addon scenario...
