### ISSUE TITLE
Does not resolve `readOnly` computed properties

### ISSUE THREAD

**Issue by lolmaus** [dwickern/ember-chrome-devtools#3]
They are shown as empty objects:

![image](https://user-images.githubusercontent.com/200884/28498013-5d2b7944-6f9d-11e7-9c9c-89d8788df080.png)

**Comment by dwickern** [comment]
@lolmaus I don't have the same issue. Do you think you could put together a reproduction?

![screen shot 2017-07-24 at 8 45 35 am](https://user-images.githubusercontent.com/752885/28531718-7dcb35fe-704c-11e7-8c81-eb614af455e7.png)

**Comment by lolmaus** [comment]
I've tried reproducing it in a clean boilerplate and failed.

But it's reproducible in my open-source codebase. I indeed do something funky there, but it does work correctly both for the Ember app itself and for Ember Inspector.

I've also noticed that when I do "Store as Global Variable" on that `Object` from my screenshot, the global variable receives the parent object. And when I do "Show as Javascript Object", the parent Ember object gets converted to a JS object and the child object appears as `AliasedProperty`.

This is the app in question: https://github.com/bread-maker/bread-maker-ember-frontend/ You can simply install it and try out.

But as the problem happens in a dependency and you may want to fiddle with it, you can do this:

```
git clone git@github.com:lolmaus/ember-zen.git
cd ember-zen
npm i
npm link
cd ..
git clone git@github.com:bread-maker/bread-maker-ember-frontend.git
cd bread-maker-ember-frontend
bower i
npm i
npm link ember-zen
ember s
```

Find the console message that starts with `[zen] state: @@INIT` and expand the object:

![image](https://user-images.githubusercontent.com/200884/28534515-a1b0e998-70a9-11e7-8037-7e9d0a24d95c.png)

You need the `node` property: 

![image](https://user-images.githubusercontent.com/200884/28534623-fce8571a-70a9-11e7-88d7-76c0d004ea96.png)

`node.settings` is an `Ember.computed.readOnly` that points at `node._content.settings`.

Here's where both properties are defined: https://github.com/lolmaus/ember-zen/blob/gen-2/addon/node.js#L169-L173

I hope you're able to reproduce the issue. I'll gladly clarify stuff, just ask.

**Comment by dwickern** [comment]
So I tracked it down, I think it's an ember bug actually: emberjs/ember.js#15545

**Comment by lolmaus** [comment]
Thank you for looking into.this, @dwickern!

**Comment by lolmaus** [comment]
So Ember team's answer is that `cacheFor` should be private?

**Comment by dwickern** [comment]
Fixed to not use `cacheFor` for `AliasedProperty`. Released as version 0.1.2

**Comment by dwickern** [comment]
I'm not sure what they will do about `cacheFor`. In its current state I don't think it should be a public API.

The only reason I use `cacheFor` is to make this plugin a little nicer to use. If a property is cached, we can display it without needing to expand the `(...)` placeholder

**Comment by lolmaus** [comment]
Thank you. :bow:

Please release.

**Comment by dwickern** [comment]
It's released, I just forgot to push the tag
